# Generated by Django 4.2.4 on 2024-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShennongMateriaMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="名称")),
                ("namepy", models.CharField(max_length=64, verbose_name="名称(含拼音)")),
                ("level", models.CharField(max_length=32, verbose_name="品级")),
                ("category", models.CharField(max_length=32, verbose_name="类别")),
                ("feature", models.CharField(max_length=32, verbose_name="性味")),
                ("wei", models.CharField(max_length=32, verbose_name="味")),
                ("xing", models.CharField(max_length=32, verbose_name="性")),
                ("meridian", models.CharField(max_length=32, verbose_name="归经")),
                ("original", models.CharField(max_length=128, verbose_name="原文")),
            ],
        ),
        migrations.CreateModel(
            name="TyphoidFeverAndMiscellaneousDiseases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescriptionName",
                    models.CharField(max_length=32, verbose_name="药名"),
                ),
                ("prescription", models.CharField(max_length=64, verbose_name="药方")),
                ("medical", models.CharField(max_length=64, verbose_name="药物")),
            ],
        ),
    ]
