# Generated by Django 4.2.4 on 2024-04-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shennongmateriamedical",
            name="id",
        ),
        migrations.RemoveField(
            model_name="typhoidfeverandmiscellaneousdiseases",
            name="id",
        ),
        migrations.AlterField(
            model_name="shennongmateriamedical",
            name="name",
            field=models.CharField(
                max_length=64, primary_key=True, serialize=False, verbose_name="名称"
            ),
        ),
        migrations.AlterField(
            model_name="typhoidfeverandmiscellaneousdiseases",
            name="prescriptionName",
            field=models.CharField(
                max_length=32, primary_key=True, serialize=False, verbose_name="药名"
            ),
        ),
    ]
